### ISSUE TITLE
Error when deleting a user with occ

### ISSUE THREAD

**Issue by Emi94** [splitt3r/mindmaps#59]
When I delete a user with the occ script I get this error:
```
An unhandled exception has been thrown:
Error: Call to a member function getUID() on null in /var/www/nextcloud/apps/circles/lib/Api/v1/Circles.php:185
Stack trace:
#0 /var/www/nextcloud/apps/mindmaps/lib/Db/MindmapMapper.php(131): OCA\Circles\Api\v1\Circles::listCircles(15)
#1 /var/www/nextcloud/apps/mindmaps/lib/AppInfo/Application.php(69): OCA\Mindmaps\Db\MindmapMapper->findAll('test22')
#2 [internal function]: OCA\Mindmaps\AppInfo\Application->OCA\Mindmaps\AppInfo\{closure}(Object(OC\User\User))
#3 /var/www/nextcloud/lib/private/Hooks/EmitterTrait.php(99): call_user_func_array(Object(Closure), Array)
#4 /var/www/nextcloud/lib/private/Hooks/PublicEmitter.php(36): OC\Hooks\BasicEmitter->emit('\\OC\\User', 'postDelete', Array)
#5 /var/www/nextcloud/lib/private/User/User.php(247): OC\Hooks\PublicEmitter->emit('\\OC\\User', 'postDelete', Array)
#6 /var/www/nextcloud/core/Command/User/Delete.php(64): OC\User\User->delete()
#7 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(264): OC\Core\Command\User\Delete->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/nextcloud/3rdparty/symfony/console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/nextcloud/3rdparty/symfony/console/Application.php(228): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\User\Delete), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/nextcloud/3rdparty/symfony/console/Application.php(130): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/nextcloud/lib/private/Console/Application.php(173): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/nextcloud/console.php(90): OC\Console\Application->run()
#13 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#14 {main}
```
My Nextcloud version is 13.0.4, Circle 0.14.0, Mindmaps 0.1.0 and PostgreSQL 9.5

(@splitt3r I recreated the issue on the mindmaps repo as you requested here: https://github.com/nextcloud/circles/issues/211)

**Comment by splitt3r** [comment]
Thank you. I will have a look at it.

**Comment by splitt3r** [comment]
Could you give me some extra info about the strucutre? Is Is it a Circle with a user that created a Mindmap?

**Comment by Emi94** [comment]
I removed some users this morning that I'm pretty sure they didn't create any mindmaps and might not have been in any circle either.

One detail that I forgot to mention is that they were LDAP users. After deleting a user from LDAP, Nextcloud detects that the user is not available in LDAP anymore and puts it in a remnants list from were I delete them with the occ script.

Just in case you didn't know, local users are found in DB table oc_users while LDAP users are kept in oc_accounts table. Maybe this has something to do with the error.

**Comment by splitt3r** [comment]
You are right i didn`t know that. I will try to set up a test instance with docker. Thanks for the hint.
